const ProductCategoryData = [
    {
        id: 1,
        ShopCategory: "Kirana shop",
        KiranaProductCategories: [
            "Fruits & Vegetables",
            "Atta,Rice & Dal",
            "Home & Office",
            "Daily ,Bread & egg",
            "Cold Drinks & Juice",
            "Snacks & Munchies",
            "Breakfast & Instant Food",
            "Tea ,Coffee & Health Drinks",
            "Sauces & Spread",
            "Cleaning Essentials",
            "Sweet Tooth",
            "Bakery & Biscuits",
        ],
    },
    {
        id: 2,
        ShopCategory: "Clothes shop",
        ClothesProductCategories: [
            "Jeans",
            "T-Shirts & Shirts",
            "Trousers",
            "Kurta & Sets",
            "Accessories",
            "Dresses",
            "Tops & Tees",
            "Kurti & Sets",
            "Sarees",
            "Heels & Flats",
            "Footwear",
        ],
    },
    {
        id: 3,
        ShopCategory: "Medical shop",
        MedicalProductCategories: [
            "Vitamins & Supplements",
            "Nutritional Drinks",
            "Personal Care",
            "Ayruveda",
            "Pain Relief",
            "Homeopathy",
            "Health Condition",
            "Accessories & Wearables",
            "Diabetic Care",
            "Mother and Baby Care",
            "Health Food and Drinks",
            "Healthcare Devices",
            "Home Care",
            "Skin Care",
            "Pet Care",
        ],
    },
    {
        id: 4,
        ShopCategory: "Electronics Shop",
        ElectronicsProductCategories: [
            "Laptops & Desktops & Computer Accessories",
            "Headphones",
            "Smart Wearables",
            "Styling Devices",
            "Cameras",
            "Tablets",
            "Mobile Accessories",,
            "Speakers & Video",
            "Gaming Accessories",
            "TVs & Smart Televisions",
            "Washing Machines & ",
            "Kitchen Appliances",
            "Air Conditioners & Fans & Air Coolers",
            "Home Appliances",
            "Microwace Ovens",
        ],
    },
];

export default ProductCategoryData;
