export const KiranaProductCategoryData = {
    id: 1,
    ShopCategory: "Kirana shop",
    KiranaProductCategories: [
        // "All",
        "Fruits And Vegetables",
        "Atta,Rice And Dal",
        "Home And Office",
        "Daily ,Bread And egg",
        "Cold Drinks And Juice",
        "Snacks And Munchies",
        "Breakfast And Instant Food",
        "Tea ,Coffee And Health Drinks",
        "Sauces And Spread",
        "Cleaning Essentials",
        "Sweet Tooth",
        "Bakery And Biscuits",
    ],
};

export const ClothesProductCategoryData = {
    id: 2,
    ShopCategory: "Clothes shop",
    ClothesProductCategories: [
        // "All",
        "Jeans",
        "T-Shirts And Shirts",
        "Trousers",
        "Kurta And Sets",
        "Accessories",
        "Dresses",
        "Tops And Tees",
        "Kurti And Sets",
        "Sarees",
        "Heels And Flats",
        "Footwear",
    ],
};

export const MedicalProductCategoryData = {
    id: 3,
    ShopCategory: "Medical shop",
    MedicalProductCategories: [
        // "All",
        "Vitamins And Supplements",
        "Nutritional Drinks",
        "Personal Care",
        "Ayruveda",
        "Pain Relief",
        "Homeopathy",
        "Health Condition",
        "Accessories And Wearables",
        "Diabetic Care",
        "Mother and Baby Care",
        "Health Food and Drinks",
        "Healthcare Devices",
        "Home Care",
        "Skin Care",
        "Pet Care",
    ],
};

export const ElectronicsProductCategoryData = {
    id: 4,
    ShopCategory: "Electronics Shop",
    ElectronicsProductCategories: [
        // "All",
        "Laptops And Desktops And Computer Accessories",
        "Headphones",
        "Smart Wearables",
        "Styling Devices",
        "Cameras",
        "Tablets",
        "Mobile Accessories",
        "Speakers And Video",
        "Gaming Accessories",
        "TVs And Smart Televisions",
        "Washing Machines",
        "Kitchen Appliances",
        "Air Conditioners And Fans And Air Coolers",
        "Home Appliances",
        "Microwace Ovens",
    ],
};

export const ParlourProductCategoryData = {
    id: 4,
    ShopCategory: "Parlour Shop",
    ParlourServiceCategories: [
        // "All",
        "Hair cutting And color",
        "Manicure And Pedicure",
        "Threading And Face wax",
        "Facial And Cleanup",
        "Bleach And Detan",
        "Wedding special",
        "Waxing",
        "Face care",
        "Shave/beard grooming",
    ],
};
