export const KiranaProductCategoryData = {
    id: 1,
    ShopCategory: "Kirana shop",
    KiranaProductCategories: [
        // "All",
        "Fruits & Vegetables",
        "Atta,Rice & Dal",
        "Home & Office",
        "Daily ,Bread & egg",
        "Cold Drinks & Juice",
        "Snacks & Munchies",
        "Breakfast & Instant Food",
        "Tea ,Coffee & Health Drinks",
        "Sauces & Spread",
        "Cleaning Essentials",
        "Sweet Tooth",
        "Bakery & Biscuits",
    ],
};

export const ClothesProductCategoryData = {
    id: 2,
    ShopCategory: "Clothes shop",
    ClothesProductCategories: [
        // "All",
        "Jeans",
        "T-Shirts & Shirts",
        "Trousers",
        "Kurta & Sets",
        "Accessories",
        "Dresses",
        "Tops & Tees",
        "Kurti & Sets",
        "Sarees",
        "Heels & Flats",
        "Footwear",
    ],
};

export const MedicalProductCategoryData = {
    id: 3,
    ShopCategory: "Medical shop",
    MedicalProductCategories: [
        // "All",
        "Vitamins & Supplements",
        "Nutritional Drinks",
        "Personal Care",
        "Ayruveda",
        "Pain Relief",
        "Homeopathy",
        "Health Condition",
        "Accessories & Wearables",
        "Diabetic Care",
        "Mother and Baby Care",
        "Health Food and Drinks",
        "Healthcare Devices",
        "Home Care",
        "Skin Care",
        "Pet Care",
    ],
};

export const ElectronicsProductCategoryData = {
    id: 4,
    ShopCategory: "Electronics Shop",
    ElectronicsProductCategories: [
        // "All",
        "Laptops & Desktops & Computer Accessories",
        "Headphones",
        "Smart Wearables",
        "Styling Devices",
        "Cameras",
        "Tablets",
        "Mobile Accessories",
        "Speakers & Video",
        "Gaming Accessories",
        "TVs & Smart Televisions",
        "Washing Machines & ",
        "Kitchen Appliances",
        "Air Conditioners & Fans & Air Coolers",
        "Home Appliances",
        "Microwace Ovens",
    ],
};

export const ParlourProductCategoryData = {
    id: 4,
    ShopCategory: "Parlour Shop",
    ParlourServiceCategories: [
        // "All",
        "Hair cutting & color",
        "Manicure & Pedicure",
        "Threading & Face wax",
        "Facial & Cleanup",
        "Bleach & Detan",
        "Wedding special",
        "Waxing",
        "Face care",
        "Shave/beard grooming",
    ],
};
